[[client]]
server_addr = "120.46.221.65"
server_port = 33445
accept_conflict = false
retry_times = 3
protocol = "tcp"

[[client.link]]
local_addr = "127.0.0.1"
local_port = 22
remote_port = 55323
protocol = "tcp"

[[client.link]]
local_addr = "127.0.0.1"
local_port = 5000
remote_port = 5525
protocol = "tcp"

[client.tcp_config]
