[[client]]
server_addr = "127.0.0.1"
server_port = 33445
accept_conflict = false
protocol = "tcp"

[[client.link]]
client_port = 56
server_port = 55
protocol = "udp"

[[client.link]]
client_port = 5000
server_port = 5525
protocol = "tcp"

[client.tcp_config]
