[[client]]
server_addr = "127.0.0.1"
server_port = 33445
accept_conflict = false
protocol = "tcp"

[[client.link]]
client_port = 5051
server_port = 55553
protocol = "tcp"

[[client.link]]
client_port = 5000
server_port = 53553
protocol = "tcp"

[[client.link]]
client_port = 6000
server_port = 23543
protocol = "tcp"

[client.tcp_config]
token = "fdasfdasfasdfasdfasdf"
